In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [9]:
arr1: np.array = np.array([2, 3, 4, 5, 5])
arr2: np.array = np.arange(5)

In [4]:
type(arr1), arr1.shape

(numpy.ndarray, (5,))

In [10]:
arr3 = np.zeros(5)
print(arr3)

[0. 0. 0. 0. 0.]


In [11]:
print(f"""
Soma de todos os elementos: {np.sum(arr1)}
O protudo dos elementos: {np.prod(arr1)}
Soma acumulada: {np.cumsum(arr1)}
Adição entre array: {np.add(arr1, arr2)}
""")


Soma de todos os elementos: 19
O protudo dos elementos: 600
Soma acumulada: [ 2  5  9 14 19]
Adição entre array: [2 4 6 8 9]



In [23]:
matriz1 = np.array([[2, 4], [5, 5]])
matriz2 = np.array([[3, 2], [4, 4]])
print(f"""
Dimensões da primeira matriz: {matriz1.shape}
{matriz1}

Dimensõesda segunda matriz: {matriz2.shape}
{matriz2}
""")

print(f'{np.dot(matriz1, matriz2)}')


Dimensões da primeira matriz: (2, 2)
[[2 4]
 [5 5]]

Dimensõesda segunda matriz: (2, 2)
[[3 2]
 [4 4]]

[[22 20]
 [35 30]]
